// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE

import {amqtt} from "./asyncmqtt.js"

// END EXTRA CODE

/**
 * @param {string} mqttServerURL - Example : "ws://192.168.222.129:9001"
 * @param {string} topic
 * @param {string} payload
 * @returns {Promise.<void>}
 */
export async function MQTT_Front_Publish(mqttServerURL, topic, payload) {
	// BEGIN USER CODE

	const client = await amqtt.connectAsync(mqttServerURL)

	try {
		await client.publish(topic, payload);
		await client.end();
		console.log("Publish Done");
	} catch (e){
		// Do something about it!
		console.log(e.stack);
		//process.exit();
	}		
	
	// END USER CODE
}
